let productos = [
    {
        id: 1,
        nombre: "Remera Asuka",
        precio: 10000,
        img: "../img/remeraAsuka.png",
        categoria: "remeras",
    },
    {
        id: 2,
        nombre: "Remera Crisis",
        precio: 10000,
        img: "../img/remeraCrisisBlanca.png",
        categoria: "remeras",
    },
    {
        id: 3,
        nombre: "Remera Miau",
        precio: 12000,
        img: "../img/remeraMiau.png",
        categoria: "remeras",
    },
    {
        id: 4,
        nombre: "Remera Michu",
        precio: 13000,
        img: "../img/remeraMichu.png",
        categoria: "remeras",
    },
    {
        id: 5,
        nombre: "Remera Moonstick",
        precio: 9000,
        img: "../img/remeraMoonstick.png",
        categoria: "remeras",
    },
    {
        id: 6,
        nombre: "Remera Roll",
        precio: 11000,
        img: "../img/remeraRoll.png",
        categoria: "remeras",
    },
    {
        id: 7,
        nombre: "Buzo Blacklady",
        precio: 12000,
        img: "../img/buzoBlackLady.png",
        categoria: "buzos",
    },
    {
        id: 8,
        nombre: "Buzo Flowers Time",
        precio: 10000,
        img: "../img/buzoFlowersTime.png",
        categoria: "buzos",
    },
    {
        id: 9,
        nombre: "Buzo Pandemia",
        precio: 10000,
        img: "../img/buzoPandemia.png",
        categoria: "buzos",
    },
    {
        id: 10,
        nombre: "Remera Octopus",
        precio: 13000,
        img: "../img/buzoOctopus.png",
        categoria: "buzos",
    },
    {
        id: 11,
        nombre: "Buzo Serena",
        precio: 9000,
        img: "../img/buzoSerena.png",
        categoria: "buzos",
    },
    {
        id: 12,
        nombre: "Buzo Xino",
        precio: 11000,
        img: "../img/buzoXino.png",
        categoria: "buzos",
    },
    {
        id: 13,
        nombre: "David",
        precio: 10000,
        img: "../img/printDavid.png",
        categoria: "prints",
    },
    {
        id: 14,
        nombre: "Ecstasy",
        precio: 10000,
        img: "../img/printEcstasy.png",
        categoria: "prints",
    },
    {
        id: 15,
        nombre: "Miau",
        precio: 12000,
        img: "../img/printMiau.png",
        categoria: "prints",
    },
    {
        id: 16,
        nombre: "Moonstick",
        precio: 13000,
        img: "../img/printMoonStick.png",
        categoria: "prints",
    },
    {
        id: 17,
        nombre: "Venus",
        precio: 9000,
        img: "../img/printVenus.png",
        categoria: "prints",
    },
    {
        id: 18,
        nombre: "Reunión",
        precio: 11000,
        img: "../img/printReunion.png",
        categoria: "prints",
    },
];